### ISSUE TITLE
Incorrect gradient in ex2

### ISSUE THREAD

**Issue by art-yg** [schneems/Octave#12]
Richard,

There is a mistake in ex2

File: Octave/mlclass-ex2/mlclass-ex2/costFunctionReg.m

> grad = (1/m)*(X'*(h-y)+lambda*theta_reg);

Correct:

> grad = 1/m * X' * (h - y) + lambda/m * theta_reg;

Artem

**Comment by FranklinYu** [comment]
What's different? He just extracted common factor `1/m`.

**Comment by art-yg** [comment]
No idea why I posted this and where I took the first equation from. Sorry.
